-- MySQL Script generated by MySQL Workbench
-- Mon Nov  2 21:21:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teacher` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `department_id` INT NOT NULL,
  `phone_number` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Teacher_Department_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_Teacher_Department`
    FOREIGN KEY (`department_id`)
    REFERENCES `mydb`.`Department` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Subject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `hours` INT NULL,
  `credits` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Building` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `creation_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NULL,
  `capacity` INT NULL,
  `building_id` INT NOT NULL,
  PRIMARY KEY (`id`, `building_id`),
  INDEX `fk_Room_Building1_idx` (`building_id` ASC) VISIBLE,
  CONSTRAINT `fk_Room_Building1`
    FOREIGN KEY (`building_id`)
    REFERENCES `mydb`.`Building` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ReservationRoom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ReservationRoom` (
  `teacher_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NULL,
  `finishing_date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Teacher_has_Aula_Aula1_idx` (`room_id` ASC) VISIBLE,
  INDEX `fk_Teacher_has_Aula_Teacher1_idx` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `fk_Teacher_has_Aula_Teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`Teacher` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Teacher_has_Aula_Aula1`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`Room` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teach` (
  `subject_id` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_Subject_has_Teacher_Teacher1_idx` (`teacher_id` ASC) VISIBLE,
  INDEX `fk_Subject_has_Teacher_Subject1_idx` (`subject_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Subject_has_Teacher_Subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `mydb`.`Subject` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Subject_has_Teacher_Teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`Teacher` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Library` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `numPages` INT NULL,
  `year` INT NULL,
  `library_id` INT NOT NULL,
  PRIMARY KEY (`id`, `library_id`),
  INDEX `fk_Book_Library1_idx` (`library_id` ASC) VISIBLE,
  CONSTRAINT `fk_Book_Library1`
    FOREIGN KEY (`library_id`)
    REFERENCES `mydb`.`Library` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation` (
  `student_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `date_return` DATE NULL,
  INDEX `fk_Student_has_Book_Book1_idx` (`book_id` ASC) VISIBLE,
  INDEX `fk_Student_has_Book_Student1_idx` (`student_id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `date`),
  CONSTRAINT `fk_Student_has_Book_Student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Student_has_Book_Book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `mydb`.`Book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mark` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mark` VARCHAR(45) NOT NULL,
  `number_mark` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Study`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Study` (
  `student_id` INT NOT NULL,
  `teach_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_Student_has_Teach_Teach1_idx` (`teach_id` ASC) VISIBLE,
  INDEX `fk_Student_has_Teach_Student1_idx` (`student_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Student_has_Teach_Student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Teach_Teach1`
    FOREIGN KEY (`teach_id`)
    REFERENCES `mydb`.`Teach` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Exam` (
  `mark_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `study_id` INT NOT NULL,
  PRIMARY KEY (`id`, `study_id`),
  INDEX `fk_Study_has_Mark_Mark1_idx` (`mark_id` ASC) VISIBLE,
  INDEX `fk_Study_has_Mark_Study1_idx` (`study_id` ASC) VISIBLE,
  CONSTRAINT `fk_Study_has_Mark_Mark1`
    FOREIGN KEY (`mark_id`)
    REFERENCES `mydb`.`Mark` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Study_has_Mark_Study1`
    FOREIGN KEY (`study_id`)
    REFERENCES `mydb`.`Study` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
